### ISSUE TITLE
How to update the maxLength of ICGVideoTrimmer.

### ISSUE THREAD

**Issue by ajay2c9** [DrustZ/ICGVideoTrimmer_extend#1]
I want to update the max length of the trimmer view.how to update without disturbing UI. i have a video of 7 min in local path i want to save 25 of video with trimming (not continuously).First i assign the max length as 25. I trimmed the video of 8 seconds . and saved in localpath. Here i want to change the maxlength of the trimmer view from 25 to 17. is it possible in to change the maxlength.
if yes please give suggestions.

I have multiple video URls (localpath videos) . is it possible to play multiple videos continuously one after another using this player.

Please give suggestions
Thank you

**Comment by DrustZ** [comment]
Hi there, 

I think there're properties in ICGVideoTrimmer:

```objective-c
// Maximum length for the trimmed video
@property (assign, nonatomic) CGFloat maxLength;

// Minimum length for the trimmed video
@property (assign, nonatomic) CGFloat minLength;

```
and you can just change them.

For your second question, you can merge them into one file in advance, then load them in the view.

**Comment by ajay2c9** [comment]
Hi.
Thank you for replying.
I see the min and max length. After setting the max length how to know that trimmer maxlength while adjust the right and left view and how to get the trimming length while adjusting the left and right view in the trimmer view.

**Comment by DrustZ** [comment]
You can also find the property 

```objective-c
// Left trimmer position
@property (readonly, nonatomic) NSTimeInterval startTime;

// Right trimmer position
@property (readonly, nonatomic) NSTimeInterval endTime;
```

Please first read the code of ``ICGVideoTrimmerView.h``  and related files if you have any other questions.

**Comment by ajay2c9** [comment]
Hi, 
I am asking about the trimming time i.e  The trimmed video is 2 min or 3min i am asking about that. I am using the start time and end time for playing the video in AVPlayer. For  calculating and changing the max length i asked about the trimmed video time.
