### ISSUE TITLE
Max length is not updated in the trimmer view

### ISSUE THREAD

**Issue by ajay2c9** [DrustZ/ICGVideoTrimmer_extend#2]
want to update the max length of the trimmer view.I have a video of 7 min in local path i want to save 25 of video with trimming (not continuously).First i assign the max length as 25. I trimmed the video of 8 seconds . and saved in localpath. Here i want to change the maxlength of the trimmer view from 25 to 17. first I used this code with max length as 25 seconds.

[self.trimmerView setThemeColor:[UIColor lightGrayColor]];
    [self.trimmerView setAsset:self.asset];
    [self.trimmerView setShowsRulerView:YES];
    [self.trimmerView setDelegate:self];
    self.trimmerView.maxLength=25;
   [self.trimmerView resetSubviews];
   [self.playerview setVideoAsset:self.asset];

After trimming some part of video and saved the trimmed part (ex: i trimmed 8 seconds and saved). Now i want to change the maxlength as 17 (25-8) . I write the code of line like this in trim button after saving the video.

    self.trimmerView.maxLength=17;
  Here the trimmer view (below image part) is not updated. the slider is updated tomax as 25 sec it is not restricted.
![screen shot 2017-04-05 at 7 56 51 pm](https://cloud.githubusercontent.com/assets/9112899/24710255/3a56370a-1a3a-11e7-80dc-ca763cfaa20c.png)

if i use the below fro update max length like this

[self.trimmerView setThemeColor:[UIColor lightGrayColor]];
    [self.trimmerView setAsset:self.asset];
    [self.trimmerView setShowsRulerView:YES];
    [self.trimmerView setDelegate:self];
    self.trimmerView.maxLength=17;
   [self.trimmerView resetSubviews];

Sometimes the images are displaying very small and video is playing from starting.

please give suggestion to update the maxlength of the trimmer view with the update of trimmer view slider(image displayed above).

**Comment by DrustZ** [comment]
Hi, if you want to implement what you said, I think you should follow these steps:

- First, let the user trim the video and save it. (let's say a 8-second video part) 
- Merge the remaining video parts together and save them as a new local file ( in your example, the new video is 17s)
- Back to the trimView, and update the parameters in functions like ViewWillAppear, remember to set the asset to the new file, and call resetSubviews.

**Comment by ajay2c9** [comment]
Hi, 
I am using this trimmer view implement like a coub app. i am downloading the multiple videos and showing in trimmer views and playing in AVPlayer. I trim the multiple videos in the same viewController and player continuously without merging (like coub). But i cannot adjust or update the maxlength of the trimmer view after trimming the videos. please give suggestions for change the maxlength like implemented in coub.

Thank you

**Comment by DrustZ** [comment]
if so, I guess you can hold an array storing the paths of the multiple videos, and let the player play continuously, and when the user trimmed the video, you can merge them in background. 

For maxlength adjustment, I still think that calling resetSubviews will do. Try to set all parameters correctly and don't forget to load the new video files. If it still doesn't work, you can simply realloc a new trimmerview or even a new viewcontroller.

**Comment by ajay2c9** [comment]
Thank you for Suggestion. I have another small doubt.
I want to use player view in my project. I have 3 videos assets and 3 button actions. For each asset I have starttime and endtime in each button action. When button 1 selected I will load the video asset1 with starttime and endtime by using the below
[self.playerview refreshTimePeriod:startTime end:endTime];

Here is my Doubt.
By using the starttime and endtime is it possible to display the trim position in trimmer view like below image 
![screen shot 2017-04-06 at 10 54 14 am](https://cloud.githubusercontent.com/assets/9112899/24739052/87c11eb0-1ab7-11e7-9f06-f796cff03f72.png)

Thank you

**Comment by DrustZ** [comment]
Yes, but I don't think there's a built-in function in trimmerview, you may implement by yourself.

**Comment by ajay2c9** [comment]
Thankyou
