### ISSUE TITLE
How to restrict the left and Right thumbview moving when max length is reached

### ISSUE THREAD

**Issue by ajay2c9** [DrustZ/ICGVideoTrimmer_extend#3]
Hi,
How to restrict moving the left thumbview and right thumbview when particular time is set i.e when i set the length to 15 seconds , while moving the left thumbview and right thumbview is moving it is restricted to 15 seconds only. is it possible to implement this feature.

Is it possible to move the scroll the images from outside like coub App. we are scrolling the images between the left and right thumb views.

Thank you

**Comment by DrustZ** [comment]
you can programmatically move the right side when user is moving the left side. When the max time value reached, just make the right side follow the left side. Checkout the  source code to find the corresponding function.

For example, in ``moveLeftOverlayView``, you can change the right side accordingly.

**Comment by ajay2c9** [comment]
Thank you for suggestion.
I have another problem for long videos like (Ex : 20 minutes to 59 minutes videos) the ruler is not displaying. Is there any possibility to display the ruler for long videos.

**Comment by DrustZ** [comment]
Sorry, I guess you can not load the video too long, please refer to other solutions

**Comment by ajay2c9** [comment]
Ok. I have small doubt . How to scroll the video from outside the trim part. i.e Right now the scrolling is occurring in trim section only. I want to scroll the video frames from outside the trim section also to adjust the video for minimum length. is there any possibility. 

Please give Suggestions.

**Comment by ajay2c9** [comment]
Hi, 
I have another issue i.e In the trimmer view starting frames are displaying black.But the video is playing. .how to stop loading the black frames in the trimmer view.

Thank you

**Comment by ajay2c9** [comment]
I got the answer. Thank you for suggestions
